//
//  StyleKit.h
//  Tiime
//
//  Created by Brandon Beecroft on 10/29/14.
//  Copyright (c) 2014 Awesometistic, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* timeIconTargets;

// Drawing Methods
+ (void)drawTimeIconWithFrame: (CGRect)frame isPressed: (BOOL)isPressed;

// Generated Images
+ (UIImage*)imageOfTimeIconWithFrame: (CGRect)frame isPressed: (BOOL)isPressed;

@end
