//
//  StyleKit.m
//  Tiime
//
//  Created by Brandon Beecroft on 10/24/14.
//  Copyright (c) 2014 Awesometistic, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawTimeIconWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* winterGray = [UIColor colorWithRed: 0.81 green: 0.81 blue: 0.81 alpha: 1];

    //// Icons
    {
        //// circlecons_vol1
        {
            //// vol1
            {
                //// icon-clock Drawing
                UIBezierPath* iconclockPath = UIBezierPath.bezierPath;
                [iconclockPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50207 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.55)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49786 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.39) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.2)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54499 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 8.9) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 9.39) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51800 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 8.9)];
                [iconclockPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74592 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 8.9)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77328 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 8.9) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.79545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 9.39)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74592 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 11.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.79545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.61) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77291 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 11.1)];
                [iconclockPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 11.1)];
                [iconclockPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 14.4)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 15.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 15.01) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57326 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 15.5)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 14.4) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51784 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 15.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 15.01)];
                [iconclockPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 11.1)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50207 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.55) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.9) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49785 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10.71)];
                [iconclockPath closePath];
                [iconclockPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) + 1)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 1.04545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82160 * CGRectGetWidth(frame), CGRectGetMaxY(frame) + 1) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 1.04545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 3.92)];
                [iconclockPath addCurveToPoint: CGPointMake(12, 1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 1.04545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 16.08) controlPoint2: CGPointMake(18.08, 1)];
                [iconclockPath addCurveToPoint: CGPointMake(1, 12) controlPoint1: CGPointMake(5.92, 1) controlPoint2: CGPointMake(1, 5.92)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) + 1) controlPoint1: CGPointMake(1, 18.08) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26931 * CGRectGetWidth(frame), CGRectGetMaxY(frame) + 1)];
                [iconclockPath closePath];
                [iconclockPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 1.2)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76637 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 1.2) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 5.14)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 18.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 14.86) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76637 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 18.8)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.14545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 10) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32454 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 18.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 14.86)];
                [iconclockPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 1.2) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.14545 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 5.14) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32454 * CGRectGetWidth(frame), CGRectGetMaxY(frame) - 1.2)];
                [iconclockPath closePath];
                iconclockPath.miterLimit = 4;

                iconclockPath.usesEvenOddFillRule = YES;

                [winterGray setFill];
                [iconclockPath fill];
            }
        }
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfTimeIconWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKit drawTimeIconWithFrame: frame];

    UIImage* imageOfTimeIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTimeIcon;
}

@end
